// Generated by CoffeeScript 1.11.1
(function() {
  var dump, htaccess, index, manifest;

  index = function(context, config) {
    return "<!doctype html>\n<html manifest=\"/cache.manifest\">\n<head>\n<meta charset=\"utf-8\"/>\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=yes\"/>\n<meta name=\"apple-mobile-web-app-title\" content=\"j•graphics\">\n<link rel=\"apple-touch-icon\" href=\"/juggling-graphics.png\">\n<title>" + config.title + "</title>\n<link rel=\"stylesheet\" href=\"" + config.publicPath + context.css + "\"/>\n</head>\n<body>\n<div id=\"root\">\n</div>\n<script src=\"" + config.publicPath + context.main + "\">\n</script>\n</body>\n</html>";
  };

  manifest = function(context) {
    return "CACHE MANIFEST\n" + context.css + "\n" + context.main + "\nfavicon.ico\njuggling-graphics.png\n\n# hash (for cache-busting): " + context.stats.chunks[0].hash;
  };

  htaccess = function(context) {
    return "AddType text/cache-manifest .manifest\n\nRewriteEngine On  \nRewriteCond %{HTTPS} !=on  \nRewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]  \n\nOptions -Indexes\n\n<Files cache.manifest>\nFileETag None\nHeader unset ETag\nHeader set Cache-Control \"max-age=0, no-cache, no-store, must-revalidate\"\nHeader set Pragma \"no-cache\"\nHeader set Expires \"Wed, 11 Jan 1984 05:00:00 GMT\"\n</Files>";
  };

  dump = function(context) {
    return "" + (JSON.stringify(context));
  };

  module.exports = {
    htaccess: htaccess,
    manifest: manifest,
    index: index,
    dump: dump
  };

}).call(this);
